maxSurge:       25%
maxUnavailable: 25%
containerRepo: 195443952464.dkr.ecr.us-east-1.amazonaws.com/illuminati/frontend
buildVersion: latest
cpuRequests: 100m
memoryRequests: 128Mi
cpuLimit: 200m
memorylimit: 256Mi
healthPath: /
containerPort: 80
minReplicas: 1
maxReplicas: 20
cpuAverageUtilization: 70
memoryAverageUtilization: 70
dnsZones: illuminati-core5.pp.ua


ingress:
  enabled: true
  host: illuminati-core5.pp.ua
  http:
    paths:
      - path: /
        pathType: Prefix