maxSurge:       25%
maxUnavailable: 25%
#Use your ECR or Docker Hub image
containerRepo: myrepo/illuminati-frontend-example
buildVersion: v1.0.1
cpuRequests: 100m
memoryRequests: 128Mi
cpuLimit: 200m
memorylimit: 256Mi
healthPath: /
containerPort: 80
minReplicas: 1
maxReplicas: 20
cpuAverageUtilization: 70
memoryAverageUtilization: 70
dnsZones: illuminati-core5.pp.ua


ingress:
  enabled: true
  host: illuminati-core5.pp.ua
  http:
    paths:
      - path: /
        pathType: Prefix