maxSurge:       25%
maxUnavailable: 25%
containerRepo: 896015496924.dkr.ecr.us-east-1.amazonaws.com/backend_stage
buildVersion: 1.0.3
cpuRequests: 100m
memoryRequests: 128Mi
cpuLimit: 200m
memorylimit: 256Mi
healthPath: /api/health/
containerPort: 8000
minReplicas: 1
maxReplicas: 20
cpuAverageUtilization: 70
memoryAverageUtilization: 70
