maxSurge:       25%
maxUnavailable: 25%
containerRepo: 195443952464.dkr.ecr.us-east-1.amazonaws.com/illuminati/backend
buildVersion: v1.0.2
cpuRequests: 100m
memoryRequests: 128Mi
cpuLimit: 200m
memorylimit: 256Mi
healthPath: /api/health/
containerPort: 8000
minReplicas: 1
maxReplicas: 20
cpuAverageUtilization: 70
memoryAverageUtilization: 70

serviceAccount:
  name: backend-sa
