maxSurge:       25%
maxUnavailable: 25%
#Use your ECR or Docker Hub image
containerRepo: myrepo/illuminati-backend-example
buildVersion: v1.0.2
cpuRequests: 100m
memoryRequests: 128Mi
cpuLimit: 200m
memorylimit: 256Mi
healthPath: /api/health/
containerPort: 8000
minReplicas: 1
maxReplicas: 20
cpuAverageUtilization: 70
memoryAverageUtilization: 70

