apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "illuminati-email-service.fullname" . }}
  labels:
    {{- include "illuminati-email-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "illuminati-email-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "illuminati-email-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: SMTP_HOST
              value: {{ .Values.smtp.host | quote }}
            - name: SMTP_PORT
              value: {{ .Values.smtp.port | quote }}
            - name: EMAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "illuminati-email-service.fullname" . }}-smtp
                  key: username
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "illuminati-email-service.fullname" . }}-smtp
                  key: password
            - name: EMAIL_FROM
              value: {{ .Values.smtp.from | quote }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}